### ISSUE TITLE
The twitter & Slack account is not connected to the deployed site. 

### ISSUE THREAD

**Issue by ItsRoy69** [keploy/website#10]
### Current behavior

When I click on the twitter icon, it redirects to the homepage. 

### Steps to reproduce

1. Go to "Join Keploy Open Source Community"
2. Click on Read More.

**Comment by ItsRoy69** [comment]
Can I work on this issue ?

**Comment by Sonichigo** [comment]
@nehagup can you please assign @ItsRoy69 the issue.
