### ISSUE TITLE
Readme and CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by ItsRoy69** [keploy/website#15]
There are certain bugs in the readme which needs to be changed as we can see 
![image](https://user-images.githubusercontent.com/78967360/210856124-6643ac46-dadd-40ad-8985-2fd2e2e3672b.png)

And we can add CODE_OF_CONDUCT.md file to make sure contributors can go through the guidelines.

I am okay with working on this issue after you assign me @nehagup

**Comment by nehagup** [comment]
@ItsRoy69 Please go ahead. :)
